- config/database.yml
- config/unicorn.rb
#What
本番環境でunicornrailsを起動させる
#Why
サーバー環境に反映させるため
> unicornrails起動のマージテスト

- README.md
DB設計図をREADME.rbに記述した。
昨日、LGTMを頂きましたが、active_hashで固定データを管理することになりました。変更箇所にミスが確認していただくため。
> DB設計の作成(active_hashの追加)

- app/assets/stylesheets/_mercari_content.scss
- app/views/items/_mercari_content.html.haml
トップページビューの改修（コンテント部分）
headerとcontentとfooterを合体させて際にfooterに干渉しビューが崩れたため。
> トップページ完成・改修

- app/assets/stylesheets/_confirmation.scss
- app/assets/stylesheets/application.scss
- app/controllers/items_controller.rb
- app/views/items/confirmation.html.haml
- config/routes.rb
#what
商品購入の確認ページを実装した。
今回は商品が売り切れの場合のビューを実装
#why
商品のやり取りの後に必要なページだから。
> 商品購入確認ページの実装

- app/assets/stylesheets/_mypage_sidebar.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/logout.scss
- app/controllers/users_controller.rb
- app/views/items/_mercari_content.html.haml
- app/views/items/_mercari_header.html.haml
- app/views/items/_sell-btn_icon.html.haml
- app/views/items/show.html.haml
- app/views/users/_mypage_sidebar.html.haml
- app/views/users/logout.html.haml
- config/routes.rb
ユーザーのログアウトページの実装をした
ページの大部分は部分テンプレートを使用することで実装した。
https://gyazo.com/27e4a94ec35ae4d4afc46289ec0fb221
https://gyazo.com/e05303b69efde30708c1089aa65ebc5b
ユーザーがログアウトをする時に必要なページのため。
> 【マークアップ】ユーザーログアウトページの実装

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/introduction.scss
- app/assets/stylesheets/logout.scss
- app/controllers/users_controller.rb
- app/views/items/_sub_header.html.haml
- app/views/users/introduction.html.haml
- app/views/users/logout.html.haml
- config/routes.rb
ユーザープロフィール編集ページを編集した。部分テンプレートを多く使用することでhamlファイルの記述を少なくしてコードを見やすいようにした。
https://gyazo.com/db28a2e84caeb57b555cda82f742fca9
https://gyazo.com/254b0cfd2e85d36a36617bfeec94d264
https://gyazo.com/251256753161fd6adf78d9cd6439c515
ユーザが地震のプロフィールを編集するときに必要になるページだから。
> 【マークアップ】ユーザープロフィール編集ページ

- config/breadcrumbs.rb
商品詳細ページへのパンくず機能を実装した。
商品詳細ページへのパンくず機能は必要な機能のため
> 商品詳細ページのパンくず機能実装

- app/assets/items/show.scss
- app/views/items/show.html.haml
商品詳細ページのパンくず機能の実装箇所を修正した
本物のメルカリを模倣しているため配置場所を修正する必要があった。
> 商品詳細ページのパンくず機能の配置修正

- app/assets/stylesheets/edit.scss
- app/assets/stylesheets/introduction.scss
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/edit.html.haml
- app/views/users/introduction.html.haml
ユーザープロフィール編集ページにおいてニックネームと自己紹介文の編集をできるようにした。
ユーザプロフィールが編集できるうようになることで自由にプロフィールが変更できるから。
> 【サーバーサイド】ユーザープロフィール編集ページ

- app/assets/stylesheets/_mercari_header.scss
- app/controllers/items/searches_controller.rb
- app/models/item.rb
- app/views/items/_mercari_content.html.haml
- app/views/items/_mercari_header.html.haml
- app/views/items/searches/index.html.haml
- app/views/users/_mypage_mainbar.html.haml
- config/routes.rb
ログイン後に表示されるトップページのヘッダーのビューを作成した。
なお、検索フォーム作成に当たって一部、`items/searches_controller.rb`を作成した（こちらのサーバサイドは後日実装）
トップページのビューは必要要件であるため
> [WIP]ログイン後のトップページ（ヘッダー）　マークアップ

- app/assets/javascripts/show.js
- app/views/items/show.html.haml
画像にカーソルを合わせると画面が遷移する
本番環境ではこれに近い動作を行っていた
> 詳細表示の画像切り替え

- README.md
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/items/_show.scss
- app/controllers/comments_controller.rb
- app/controllers/items_controller.rb
- app/models/comment.rb
- app/models/item.rb
- app/models/item_image.rb
- app/models/user.rb
- app/views/items/_comment.html.haml
- app/views/items/show.html.haml
- config/application.rb
- config/routes.rb
- db/migrate/20200111020704_create_comments.rb
- db/schema.rb
- spec/controllers/card_controller_spec.rb
- spec/factories/card.rb
- spec/factories/comment.rb
- spec/factories/items.rb
- spec/factories/sns_credentials.rb
- spec/models/card_spec.rb
- spec/models/comment_spec.rb
- spec/models/item_spec.rb
- spec/models/sns_credentials_spec.rb
商品詳細画面にてコメント投稿機能を実装した。購入完了（buyer_idが代入）の時点でコメント投稿ボタンを押せないよう条件分岐した。
商品詳細画面にて、出品者と購入者がやりとりするため
> [WIP]コメント投稿機能の実装

- app/assets/stylesheets/items/_show.scss
- app/views/items/show.html.haml
> [WIP]売り切れ時の「sold」表示

- app/assets/javascripts/show.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/introduction.scss
- app/assets/stylesheets/items/_show.scss
- app/assets/stylesheets/users/_favorite.scss
- app/controllers/favorites_controller.rb
- app/controllers/users_controller.rb
- app/models/favorite.rb
- app/models/item.rb
- app/models/user.rb
- app/views/items/_mercari_header.html.haml
- app/views/items/show.html.haml
- app/views/shared/_favorite_item.html.haml
- app/views/users/_mypage_sidebar.html.haml
- app/views/users/favorite.html.haml
- app/views/users/introduction.html.haml
- config/routes.rb
- db/migrate/20200112005745_create_favorites.rb
- db/schema.rb
- spec/factories/favorite.rb
- spec/models/favorite_spec.rb
出品済み商品に対しての「いいね機能」を実装した。いいねをした商品の一覧は`users/favorite.html.haml`で確認できる
いいね機能を実装することで、ユーザーが商品の管理がしやすくなるため
> [WIP]いいね！機能の実装

- app/assets/javascripts/comment.js
- app/assets/stylesheets/items/_show.scss
- app/assets/stylesheets/users/_favorite.scss
- app/controllers/comments_controller.rb
- app/views/comments/create.json.jbuilder
- app/views/items/_comment.html.haml
- app/views/items/show.html.haml
コメント投稿機能にajaxを搭載した。
ユーザーの使いやすさ向上のため
> [WIP]commentの非同期実装

- app/views/items/show.html.haml
- db/schema.rb
出品者の購入ボタンの削除
自身が出品した商品は「購入画面へ進む」ボタンを押せなくなっているようにする
> [WIP]出品者の購入ボタンの削除

- app/assets/javascripts/category.js
- app/assets/javascripts/item.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/items/_edit.scss
- app/assets/stylesheets/items/_show.scss
- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/edit.html.haml
- app/views/items/show.html.haml
- app/views/users/exhibiting.html.haml
出品した商品の編集及び削除機能を実装した。
商品情報を変更できるようにするため。
> 商品編集、削除機能の実装

- app/controllers/users_controller.rb
- app/views/users/edit.html.haml
- config/routes.rb
- db/schema.rb
ユーザ本人確認ページのサーバーサイド実装をした。
変更点として新規登録時に任意の入力部分である建物名の入力の有無によってビューの表示が変わる仕様にした。
https://gyazo.com/89ebe9ca4e0b64f57d8438f490e8b574
https://gyazo.com/59f3fb7631c46891492a34d8e5d9088b
https://gyazo.com/35488f5ce0000df22216d262f235fc2d
なおユーザー本人確認ページの記述内容の保存に関しては後ほど実装の予定
mercariの完成度の向上のため。
> 【サーバサイドユーザー本人確認ページ

- app/controllers/items/searches_controller.rb
- app/models/item.rb
- app/views/items/_mercari_content.html.haml
- app/views/items/searches/_search_result.html.haml
- app/views/items/searches/index.html.haml
商品検索機能を実装した。商品のタイトルから商品を検索できる様にした。
商品を検索できることで、買いたい商品を見つけることができるため
> 【サーバサイド】商品検索Lv1　の実装

- app/controllers/addresses_controller.rb
- app/views/users/edit.html.haml
- config/routes.rb
ユーザー本人確認ページでのフォームの入力内容を保存できるように実装した
mercariの完成度の向上のため
> 【サーバーサイド】ユーザー本人確認ページ

- app/assets/stylesheets/_mercari_content.scss
- app/assets/stylesheets/items/_show.scss
- app/controllers/items_controller.rb
- app/views/items/_item_list.html.haml
- app/views/items/_seller_item_list.html.haml
- app/views/items/show.html.haml
商品詳細ページでの売り切れ表示。また、それに伴うインスタンス変数の設定とその呼び出し
ハリボテで機能として不十分だったので
> Soldout mark

- app/assets/stylesheets/logout.scss
- app/controllers/favorites_controller.rb
- app/controllers/users_controller.rb
- app/views/favorites/create.js.haml
- app/views/favorites/destroy.js.haml
- app/views/items/_favorite_ajax.html.haml
- app/views/items/show.html.haml
- app/views/users/logout.html.haml
いいね機能の非同期通信を実装した。
スプリントレビューでぜひ実装すべきと提言されたため
> [WIP]いいね機能の非同期の実装

- app/assets/stylesheets/_mercari_footer.scss
フッターにhover: textdecoration: underlineの実装をした
メルカリの完成度向上のため。
> メルカリのフッターへのhover実装

- app/views/items/_mercari_footer.html.haml
メルカリのフッター部分に関してリファクタリングをした。
具体的にはリンクに繋がる部分に関してlink_toメソッドで統一、リンク先を本物のメルカリのリンク先から#に変更した。
メルカリの質の向上のため。
> トップページのフッター部分のリファクタリング

- app/controllers/items_controller.rb
- app/views/items/_mercari_content.html.haml
カテゴリーごとの商品一覧を実装した。
ユーザーの使いやすさの観点から。
SQLの処理負荷が大きくなりすぎていないか、ご確認お願いいたします。
> [WIP]items#indexページ カテゴリーごとの表示

- Gemfile
- Gemfile.lock
- README.md
- app/models/item.rb
- app/views/layouts/application.html.haml
- app/views/layouts/registrations.html.haml
- config/environments/production.rb
本番環境にGoogle analyticsを導入した
マーケティングツールの試験導入のため
> Google analyticsの導入
